server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: sso-client
    
  thymeleaf:
    cache: false
    
  security:
    oauth2:
      client:
        registration:
          sso-client:
            client-id: sample-client
            client-secret: sample-secret
            client-name: SSO客户端
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile
            client-authentication-method: client_secret_basic
        provider:
          sso-client:
            issuer-uri: http://localhost:8080
            authorization-uri: http://localhost:8080/oauth2/authorize
            token-uri: http://localhost:8080/oauth2/token
            jwk-set-uri: http://localhost:8080/oauth2/jwks
            user-info-uri: http://localhost:8080/userinfo
            user-name-attribute: sub

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG 