server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
        secure: false
      timeout: 30m
    
spring:
  application:
    name: sso-server
    
  datasource:
    url: jdbc:h2:mem:sso-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  h2:
    console:
      enabled: true
      path: /h2-console
  
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG 